import random
dado1 = random.randint(1, 6)
dado2 = random.randint(1, 6)
dado3 = random.randint(1, 6)
dado4 = random.randint(1, 6)
dado5 = random.randint(1, 6)
dado6 = random.randint(1, 6)
dado7 = random.randint(1, 6)
dado8 = random.randint(1, 6)
dado9 = random.randint(1, 6)
dado10 = random.randint(1, 6)

print("EL NUMERO DEL DADO 1 ES: ")
print(dado1)
print("EL NUMERO DEL DADO 2 ES: ")
print(dado2)
print("EL NUMERO DEL DADO 3 ES: ")
print(dado3)
print("EL NUMERO DEL DADO 4 ES: ")
print(dado4)
print("EL NUMERO DEL DADO 5 ES: ")
print(dado5)
print("EL NUMERO DEL DADO 6 ES: ")
print(dado6)
print("EL NUMERO DEL DADO 7 ES: ")
print(dado7)
print("EL NUMERO DEL DADO 8 ES: ")
print(dado8)
print("EL NUMERO DEL DADO 9 ES: ")
print(dado9)
print("EL NUMERO DEL DADO 10 ES: ")
print(dado10)
